### ISSUE TITLE
Implement photo upload from FE to BE using the POST photo route.

### ISSUE THREAD

**Issue by jxh01753** [nc-ateam/sb-fe#23]
Requires conversation with BE team over their POST method.

JORDANS FINDINGS

after some brief readin this code should work for url extraction

// Alternatively way to get download URL
storageRef.child("users/me/profile.png").getDownloadUrl().getResult();

i think we only need .getDownloadURl()  NOT get result as that would yield us the photo itself

**Comment by jbromley94** [comment]
resolved with https://github.com/jbromley94/test-firebase-uploader
